using Tokens.Compilation.Definitions;
using Xunit;

namespace Tokens.Compilation.Binders;

public class TemplateFactoryTests
{
    [Fact]
    public void GivenDefinitionWithName_WhenCreating_ThenTemplateHasName()
    {
        var definition = new TemplateDefinition { Name = "My Template" };
        var template = TemplateFactory.Create(42UL, definition);
        Assert.Equal("My Template", template.Name);
    }

    [Fact]
    public void GivenDefinitionWithoutName_WhenCreating_ThenNameIsAutoGenerated()
    {
        var definition = new TemplateDefinition { Name = string.Empty };
        var template = TemplateFactory.Create(42UL, definition);
        Assert.StartsWith("Template_", template.Name, StringComparison.Ordinal);
    }

    [Fact]
    public void GivenDefinitionWithWhitespaceName_WhenCreating_ThenNameIsAutoGenerated()
    {
        var definition = new TemplateDefinition { Name = "   " };
        var template = TemplateFactory.Create(42UL, definition);
        Assert.StartsWith("Template_", template.Name, StringComparison.Ordinal);
    }

    [Fact]
    public void GivenId_WhenCreating_ThenTemplateHasId()
    {
        var definition = new TemplateDefinition();
        var template = TemplateFactory.Create(123UL, definition);
        Assert.Equal(123UL, template.Id);
    }

    [Fact]
    public void GivenDefinitionWithOptions_WhenCreating_ThenTemplateHasOptions()
    {
        var options = new TokenizerOptions { OutOfOrderTokens = true };
        var definition = new TemplateDefinition { Options = options };
        var template = TemplateFactory.Create(42UL, definition);
        Assert.True(template.Options.OutOfOrderTokens);
    }

    [Fact]
    public void GivenMultipleCreations_WhenNoName_ThenCounterIncrements()
    {
        var definition = new TemplateDefinition { Name = string.Empty };
        var t1 = TemplateFactory.Create(1UL, definition);
        var t2 = TemplateFactory.Create(2UL, definition);
        Assert.NotEqual(t1.Name, t2.Name);
        Assert.StartsWith("Template_", t1.Name, StringComparison.Ordinal);
        Assert.StartsWith("Template_", t2.Name, StringComparison.Ordinal);
    }
}
