using Tokens.Exceptions;
using Tokens.Transformers;
using Xunit;

namespace Tokens.Compilation;

public class TemplateCompilerTests
{
    private readonly TemplateCompiler parser = new(new TokenizerOptions());

    [Fact]
    public void GivenTemplateWithDecorator_WhenCompiling_ThenTokenHasDecorator()
    {
        var template = parser.Compile("Preamble{Token:ToDateTime(yyyy-MM-dd)}");

        Assert.Single(template.Tokens);

        var token = template.Tokens.First();

        Assert.Single(token.Decorators);

        var tokenOperator = token.Decorators.First();

        Assert.Equal(typeof(ToDateTimeTransformer), tokenOperator.DecoratorType);
        Assert.Single(tokenOperator.Parameters);
        Assert.Equal("yyyy-MM-dd", tokenOperator.Parameters[0]);
    }

    [Fact]
    public void GivenTemplateWithTrailingNewLine_WhenCompiling_ThenTokenHasDecorator()
    {
        var template = parser.Compile("Preamble{Token:ToDateTime(yyyy-MM-dd)}\n");

        Assert.Single(template.Tokens);

        var token = template.Tokens.First();

        Assert.Single(token.Decorators);

        var tokenOperator = token.Decorators.First();

        Assert.Equal(typeof(ToDateTimeTransformer), tokenOperator.DecoratorType);
        Assert.Single(tokenOperator.Parameters);
        Assert.Equal("yyyy-MM-dd", tokenOperator.Parameters[0]);
    }

    [Fact]
    public void GivenTemplateWithRequiredFlag_WhenCompiling_ThenTokenIsRequired()
    {
        var template = parser.Compile("Preamble{Token!}\n");

        Assert.Single(template.Tokens);

        var token = template.Tokens.First();

        Assert.True(token.IsRequired);
    }

    [Fact]
    public void GivenTemplateWithNoFrontMatterName_WhenCompiling_ThenNameIsAutoGenerated()
    {
        var template = parser.Compile("Preamble");

        Assert.StartsWith("Template_", template.Name);
    }

    [Fact]
    public void GivenFrontMatterWithName_WhenCompiling_ThenNameIsFromFrontMatter()
    {
        var template = parser.Compile("---\nName: My Template\n---\nPreamble");

        Assert.Equal("My Template", template.Name);
    }

    [Fact]
    public void GivenFrontMatterWithWindowsNewlines_WhenCompiling_ThenOptionsApplied()
    {
        var template = parser.Compile("---\r\nOutOfOrder: true\r\n---\r\nOne Two\r\nThree Four");

        Assert.True(template.Options.OutOfOrderTokens);
    }

    [Fact]
    public void GivenFrontMatterWithUnixNewlines_WhenCompiling_ThenOptionsApplied()
    {
        var template = parser.Compile("---\nOutOfOrder: true\n---\nOne Two\nThree Four");

        Assert.True(template.Options.OutOfOrderTokens);
    }

    [Fact]
    public void GivenEmptyContent_WhenCompiling_ThenNameIsAutoGenerated()
    {
        var template = parser.Compile("");

        Assert.StartsWith("Template_", template.Name);
    }

    [Fact]
    public void GivenFrontMatterWithTag_WhenCompiling_ThenTemplateHasTag()
    {
        var template = parser.Compile("---\nTag: tag\n---\nOne Two\nThree Four");

        Assert.Single(template.Tags);
        Assert.Equal("tag", template.Tags[0]);
    }

    [Fact]
    public void GivenFrontMatterTokenWithoutSetValue_WhenCompiling_ThenThrowsException()
    {
        Assert.Throws<TokenizerException>(() => parser.Compile("---\nset: Decorator\n---\nOne Two\nThree Four"));
    }

    [Fact]
    public void GivenFrontMatterTokenWithSetValue_WhenCompiling_ThenTokenHasName()
    {
        var template = parser.Compile("---\nset : Foo = tag\n---\nOne Two\nThree Four");

        Assert.Equal(2, template.Tokens.Count);
        Assert.Equal("Foo", template.Tokens.First().Name);
    }
}
